### PR TITLE
feat: Implement new UI design + Pre commit hooks + Eslint + Husky + Prettier + lint-staged

### PR DESCRIPTION
**Pull request by pranshuchittora**

### CODE REVIEW

**Comment by pranshuchittora** [comment]
Review Requested @pepoospina

**Comment by pepoospina** [comment]
This looks pretty gopd. I would only make sure all files are saved with prettier autoformat enabled

**Comment by pepoospina** [comment]
I manually merged this locally

**Comment by pepoospina** [comment]
Manually merged

**Pull request closed without merging**
